"""
Manual, on-demand download-speed estimate.

This is deliberately *not* part of the monitoring loop - it is only ever
invoked by an explicit user action (the dashboard's "Run speed test"
button, or `POST /api/speedtest`), never on a timer. A real bandwidth test
saturates the connection for a few seconds, which is exactly the kind of
thing that should never happen silently in the background of a tool
that's supposed to be lightweight.

Implementation choice: `requests` (a *blocking* HTTP call) run inside a
worker thread via `asyncio.to_thread`, rather than an async HTTP client.
This is a deliberate, verifiable guarantee - offloading to an OS thread
means the download genuinely cannot stall the event loop the 5-second ping
scheduler runs on, no matter how the download itself behaves (slow
server, network stall, etc.), which is easier to reason about here than
trusting every layer of an async HTTP stack to never accidentally block.
"""
from __future__ import annotations

import asyncio
import time
from dataclasses import dataclass

import requests

# Cloudflare's speed-test endpoint returns exactly the requested number of
# generated bytes, no auth, and is meant for exactly this purpose - no need
# to host our own test file or depend on a specific static file staying put
# on someone else's server.
_TEST_URL = "https://speed.cloudflare.com/__down"
_DEFAULT_SIZE_BYTES = 10_000_000  # 10 MB
_TIMEOUT_SECONDS = 15.0


@dataclass
class SpeedtestResult:
    download_mbps: float
    bytes_downloaded: int
    elapsed_seconds: float
    server: str


def _blocking_download(size_bytes: int, timeout: float) -> SpeedtestResult:
    start = time.monotonic()
    downloaded = 0
    with requests.get(_TEST_URL, params={"bytes": size_bytes}, stream=True, timeout=timeout) as resp:
        resp.raise_for_status()
        for chunk in resp.iter_content(chunk_size=65536):
            downloaded += len(chunk)
    elapsed = max(time.monotonic() - start, 0.001)
    mbps = (downloaded * 8 / 1_000_000) / elapsed
    return SpeedtestResult(
        download_mbps=round(mbps, 2),
        bytes_downloaded=downloaded,
        elapsed_seconds=round(elapsed, 2),
        server="speed.cloudflare.com",
    )


async def run_speedtest(size_bytes: int = _DEFAULT_SIZE_BYTES) -> SpeedtestResult:
    """Runs the blocking download in a worker thread so the caller's event
    loop - and every ping check scheduled on it - keeps running normally
    while this is in flight."""
    return await asyncio.to_thread(_blocking_download, size_bytes, _TIMEOUT_SECONDS)
